<?php

namespace Database\Seeders;

use App\Models\Collection;
use Illuminate\Database\Seeder;
use Carbon\Carbon;

class CollectionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $paymentStatuses = ['pending', 'partial', 'paid', 'overdue'];

        $collections = [
            [
                'project_name' => 'Office Building Renovation',
                'company_name' => 'BuildCorp Inc.',
                'project_manager_mobile' => '+1-555-0103',
                'accounting_manager_mobile' => '+1-555-0102',
                'email' => 'accounting@buildcorp.com',
                'contact_person' => 'Tom Anderson',
                'debt' => 45000.00,
                'collected_amount' => 30000.00,
                'remaining_amount_to_collect' => 15000.00,
                'amount_collected_this_month' => 10000.00,
                'agreed_payment_date' => Carbon::now()->addDays(15),
                'last_execution_date' => Carbon::now()->subDays(30),
                'last_invoice_issue_date' => Carbon::now()->subDays(25),
                'last_invoice_issuance_date' => Carbon::now()->subDays(25),
                'last_detail_sent_date' => Carbon::now()->subDays(5),
                'last_connection' => Carbon::now()->subDays(3),
                'payment_status' => 'partial',
                'cumulative_offset' => 5000.00,
                'offset_instead_of_guarantee' => 2000.00,
                'offset_instead_of_guarantee_before_vat' => 1680.67,
                'paymnet_plus' => false,
                'is_archived' => false,
                'guarantee_end_date' => Carbon::now()->addMonths(6),
                'first_line_sent_whatsapp' => true,
                'details' => 'First payment received. Awaiting second installment.',
                'second_line_sent_email_details' => 'Email reminder sent regarding remaining balance.',
                'whatsapp_2' => true,
                'details_2' => 'Follow-up WhatsApp sent. Client confirmed payment date.',
                'call_2_created' => true,
                'collection_contact' => 'Tom Anderson',
            ],
            [
                'project_name' => 'Shopping Mall Installation',
                'company_name' => 'Mall Developers Ltd.',
                'project_manager_mobile' => '+1-555-0203',
                'accounting_manager_mobile' => '+1-555-0202',
                'email' => 'accounting@malldev.com',
                'contact_person' => 'Lisa Chen',
                'debt' => 85000.00,
                'collected_amount' => 85000.00,
                'remaining_amount_to_collect' => 0.00,
                'amount_collected_this_month' => 35000.00,
                'agreed_payment_date' => Carbon::now()->subDays(10),
                'last_execution_date' => Carbon::now()->subDays(45),
                'last_invoice_issue_date' => Carbon::now()->subDays(40),
                'last_invoice_issuance_date' => Carbon::now()->subDays(40),
                'last_detail_sent_date' => Carbon::now()->subDays(20),
                'last_connection' => Carbon::now()->subDays(10),
                'payment_status' => 'paid',
                'cumulative_offset' => 0.00,
                'offset_instead_of_guarantee' => 0.00,
                'offset_instead_of_guarantee_before_vat' => 0.00,
                'paymnet_plus' => true,
                'is_archived' => false,
                'guarantee_end_date' => Carbon::now()->addMonths(12),
                'first_line_sent_whatsapp' => true,
                'details' => 'Full payment received. Project completed successfully.',
                'second_line_sent_email_details' => null,
                'whatsapp_2' => false,
                'details_2' => null,
                'call_2_created' => false,
                'collection_contact' => 'Lisa Chen',
            ],
            [
                'project_name' => 'Industrial Warehouse Setup',
                'company_name' => 'Warehouse Solutions',
                'project_manager_mobile' => '+1-555-0303',
                'accounting_manager_mobile' => '+1-555-0302',
                'email' => 'billing@warehousesol.com',
                'contact_person' => 'Mark Wilson',
                'debt' => 62000.00,
                'collected_amount' => 0.00,
                'remaining_amount_to_collect' => 62000.00,
                'amount_collected_this_month' => 0.00,
                'agreed_payment_date' => Carbon::now()->addDays(30),
                'last_execution_date' => Carbon::now()->subDays(15),
                'last_invoice_issue_date' => Carbon::now()->subDays(10),
                'last_invoice_issuance_date' => Carbon::now()->subDays(10),
                'last_detail_sent_date' => Carbon::now()->subDays(2),
                'last_connection' => Carbon::now()->subDays(1),
                'payment_status' => 'pending',
                'cumulative_offset' => 3000.00,
                'offset_instead_of_guarantee' => 3000.00,
                'offset_instead_of_guarantee_before_vat' => 2521.01,
                'paymnet_plus' => false,
                'is_archived' => false,
                'guarantee_end_date' => Carbon::now()->addMonths(9),
                'first_line_sent_whatsapp' => true,
                'details' => 'Invoice sent. Awaiting initial payment.',
                'second_line_sent_email_details' => 'Payment terms discussed. 30-day payment period agreed.',
                'whatsapp_2' => false,
                'details_2' => null,
                'call_2_created' => false,
                'collection_contact' => 'Mark Wilson',
            ],
            [
                'project_name' => 'Residential Complex Wiring',
                'company_name' => 'Urban Living Properties',
                'project_manager_mobile' => '+1-555-0403',
                'accounting_manager_mobile' => '+1-555-0402',
                'email' => 'accounts@urbanliving.com',
                'contact_person' => 'Patricia Moore',
                'debt' => 95000.00,
                'collected_amount' => 20000.00,
                'remaining_amount_to_collect' => 75000.00,
                'amount_collected_this_month' => 20000.00,
                'agreed_payment_date' => Carbon::now()->subDays(5),
                'last_execution_date' => Carbon::now()->subDays(60),
                'last_invoice_issue_date' => Carbon::now()->subDays(50),
                'last_invoice_issuance_date' => Carbon::now()->subDays(50),
                'last_detail_sent_date' => Carbon::now()->subDays(1),
                'last_connection' => Carbon::now(),
                'payment_status' => 'overdue',
                'cumulative_offset' => 8000.00,
                'offset_instead_of_guarantee' => 4000.00,
                'offset_instead_of_guarantee_before_vat' => 3361.34,
                'paymnet_plus' => false,
                'is_archived' => false,
                'guarantee_end_date' => Carbon::now()->addMonths(8),
                'first_line_sent_whatsapp' => true,
                'details' => 'First payment received. Second payment overdue.',
                'second_line_sent_email_details' => 'Multiple reminders sent. Payment delay due to cash flow issues.',
                'whatsapp_2' => true,
                'details_2' => 'Urgent follow-up. Client promises payment by end of week.',
                'call_2_created' => true,
                'collection_contact' => 'Patricia Moore',
            ],
            [
                'project_name' => 'Hospital Electrical Upgrade',
                'company_name' => 'HealthCare Systems',
                'project_manager_mobile' => '+1-555-0503',
                'accounting_manager_mobile' => '+1-555-0502',
                'email' => 'finance@healthcare-sys.com',
                'contact_person' => 'Nancy Garcia',
                'debt' => 125000.00,
                'collected_amount' => 62500.00,
                'remaining_amount_to_collect' => 62500.00,
                'amount_collected_this_month' => 0.00,
                'agreed_payment_date' => Carbon::now()->addDays(20),
                'last_execution_date' => Carbon::now()->subDays(20),
                'last_invoice_issue_date' => Carbon::now()->subDays(15),
                'last_invoice_issuance_date' => Carbon::now()->subDays(15),
                'last_detail_sent_date' => Carbon::now()->subDays(7),
                'last_connection' => Carbon::now()->subDays(5),
                'payment_status' => 'partial',
                'cumulative_offset' => 10000.00,
                'offset_instead_of_guarantee' => 5000.00,
                'offset_instead_of_guarantee_before_vat' => 4201.68,
                'paymnet_plus' => true,
                'is_archived' => false,
                'guarantee_end_date' => Carbon::now()->addMonths(12),
                'first_line_sent_whatsapp' => true,
                'details' => '50% payment received. Second installment scheduled.',
                'second_line_sent_email_details' => 'Hospital accounting confirmed next payment date.',
                'whatsapp_2' => false,
                'details_2' => null,
                'call_2_created' => false,
                'collection_contact' => 'Nancy Garcia',
            ],
        ];

        foreach ($collections as $collection) {
            Collection::create($collection);
        }
    }
}
